### ISSUE TITLE
Track: Convert cost of recipe to their own currency

### ISSUE THREAD

**Issue by tsjoh** [joh-ann/whats-cookin#74]
Free Currency Rates API: https://github.com/fawazahmed0/currency-api#readme

NPM library: https://www.npmjs.com/package/currency-exchanger-js?activeTab=readme

Chosen currencies:

1. Canadian Dollar
2. English Pound
3. Japanese Yen
4. Hong Kong Dollar
5. Zew Zealand Dollar
6. Thai Baht
7. :us::us::us::us::us::us:
8. Indian Rupee
9. Ethereum Cryptocurrency
10. Dogecoin Cryptocurrency

**Comment by pitter3** [comment]
Canadian Dollar: $ or CAD

British Pound: £ or GBP

Japanese Yen: ¥ or JPY

Hong Kong Dollar: $ or HKD

New Zealand Dollar: $ or NZD

Thai Baht: ฿ or THB

Indian Rupee: ₹ or INR
